
services:
  bff:
    build: ./bff
    ports: ["8080:8080"]
    environment:
      - CATALOG_URL=http://catalog_service:8001
      - CART_URL=http://cart_service:8002
      - ORDER_URL=http://order_service:8003
      - PAYMENT_URL=http://payment_service:8004
      - RECO_URL=http://recommendation_service:8005
      - SHIPPING_URL=http://shipping_service:8006
      - DEFAULT_LOCALE=pt-BR
      - DEFAULT_CURRENCY=BRL
      - ALLOWED_PAYMENT_METHODS=card,pix,boleto,wallet
      - RECO_STRATEGY=content
      - RECO_ENABLED=true
      - CHECKOUT_GUEST=true
      - CHECKOUT_ONECLICK=false
      - SHIPPING_ENABLED=true
      - SHIPPING_MODE=transportadora
    depends_on:
      - catalog_service
      - cart_service
      - order_service
      - payment_service
      - recommendation_service
      - shipping_service

  catalog_service:
    build: ./catalog_service
    volumes: ["catalog_data:/data"]
    environment: ["SQLITE_PATH=/data/catalog.db"]
    ports: ["8001:8001"]

  cart_service:
    build: ./cart_service
    ports: ["8002:8002"]

  payment_service:
    build: ./payment_service
    ports: ["8004:8004"]

  order_service:
    build: ./order_service
    volumes: ["order_data:/data"]
    environment:
      - SQLITE_PATH=/data/orders.db
      - CATALOG_URL=http://catalog_service:8001
      - CART_URL=http://cart_service:8002
      - PAYMENT_URL=http://payment_service:8004
    ports: ["8003:8003"]
    depends_on: [catalog_service, cart_service, payment_service]

  recommendation_service:
    build: ./recommendation_service
    environment: ["CATALOG_URL=http://catalog_service:8001"]
    ports: ["8005:8005"]
    depends_on: [catalog_service]

  shipping_service:
    build: ./shipping_service
    environment: ["CATALOG_URL=http://catalog_service:8001"]
    ports: ["8006:8006"]
    depends_on: [catalog_service]

volumes:
  catalog_data: {}
  order_data: {}
